name: td_tcc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alembic==1.12.0
      - anyio==4.0.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - azure-core==1.26.4
      - azure-storage-blob==12.16.0
      - blinker==1.6.2
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - cmake==3.27.5
      - contourpy==1.1.1
      - cryptography==41.0.4
      - cycler==0.11.0
      - databricks-cli==0.17.7
      - datasets==2.12.0
      - dill==0.3.6
      - docker==6.1.3
      - efficientnet-pytorch==0.7.1
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - fastapi==0.95.1
      - filelock==3.12.4
      - flask==2.3.3
      - fonttools==4.42.1
      - frozenlist==1.4.0
      - fsspec==2023.9.1
      - gitdb==4.0.10
      - gitpython==3.1.36
      - greenlet==2.0.2
      - gunicorn==20.1.0
      - h11==0.14.0
      - huggingface-hub==0.17.2
      - idna==3.4
      - imageio==2.31.3
      - imgaug==0.4.0
      - importlib-metadata==6.8.0
      - isodate==0.6.1
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lit==16.0.6
      - mako==1.2.4
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - mlflow==2.3.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - munch==4.0.0
      - networkx==3.1
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - opencv-contrib-python==4.7.0.72
      - opencv-python==4.8.0.76
      - packaging==23.1
      - pandas==2.1.0
      - pillow==9.5.0
      - pretrainedmodels==0.7.4
      - protobuf==4.24.3
      - pyarrow==11.0.0
      - pycparser==2.21
      - pydantic==1.10.12
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-multipart==0.0.5
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - querystring-parser==1.2.4
      - regex==2023.8.8
      - requests==2.31.0
      - responses==0.18.0
      - safetensors==0.3.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - seaborn==0.12.2
      - segmentation-models-pytorch==0.3.3
      - shapely==2.0.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - sqlalchemy==2.0.21
      - sqlparse==0.4.4
      - starlette==0.26.1
      - sympy==1.12
      - tabulate==0.9.0
      - threadpoolctl==3.2.0
      - tifffile==2023.9.18
      - timm==0.9.2
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchmetrics==0.11.4
      - torchvision==0.15.2
      - tqdm==4.66.1
      - transformers==4.27.4
      - triton==2.0.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - uvicorn==0.22.0
      - websocket-client==1.6.3
      - werkzeug==2.3.7
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.17.0